### ISSUE TITLE
Better ResizeObserver hook

### ISSUE THREAD

**Issue by thednp** [kobaltedev/kobalte#434] opened 2024-06-25 05:16 UTC
I noticed some performance issues, probably some memory leaks related, and I noticed you're using an interesting ResizeObserver implementation, which I think it's not good enough because you're looping through all nodes and it's an expensive operation. Also you're missing out other rect attributes such as x, y, top, bottom, etc.

Here's an example of a potentially better implementation (inspired by useIntersectionObserver hook from React):

```tsx
import { createEffect, onCleanup, createSignal } from 'solid-js';

export function useResizeObserver() {
  const [entry, setEntry] = createSignal<ResizeObserverEntry>();
  let previousObserver: ResizeObserver;

  const customRef = <T extends Element>(node: T) => {
    if (previousObserver) {
      previousObserver.disconnect();
    }
    if (node?.nodeType === Node.ELEMENT_NODE) {
      previousObserver = new ResizeObserver(
        ([entry]) => {
          setEntry(entry);
        },
      );
      previousObserver.observe(node);
    }
  };

  createEffect(() => {
    if (previousObserver) {
      onCleanup(() => previousObserver.disconnect());
    }
  });

  return [customRef, entry] as [typeof customRef, typeof entry];
}
```

Usage

```tsx
export default function Home() {
  const [resizeRef, observerEntry] = useResizeObserver();

  createEffect(() => {
    console.log(observerEntry());
  })

  return (
      <main ref={resizeRef} class="w-full h-full">
        Demo content
     </main>
  )
}
```
A similar implementation can be done with IntersectionObserver.

Please let me know what you think.

**Comment by jer3m01** [comment] 2024-06-29 01:18
cc @GiyoMoon

**Comment by GiyoMoon** [comment] 2024-06-29 13:52
Good call about the loop. I didn't fully understand how the entries work and that the loop isn't required as there always will be a single entry in this use case. I'll fix this.

But why do you think that this would cause memory leaks? It's a single loop, looping over an array with one entry.

**Comment by thednp** [comment] 2024-06-29 15:42
I think you should test the difference yourself, basically you're adding additional scopes and additional effects for just 2 values, instead of getting all values with less work.

The way hooks should work generally is to attach logic to DOM nodes like they own them, native, the customRef callback is a genius spark of power.

**Comment by GiyoMoon** [comment] 2024-06-29 17:19
> for just 2 values, instead of getting all values with minimal work.

Well, we only need these two values in our use case. No need to keep the whole entry in memory if we don't need it.
And imo it perfectly makes sense to use an effect here, as we're working with the DOM and need to cleanup after us. Like you're using one too to disconnect the observer. I don't see how our implementation would cause any noticeable performance issues. Usually, laggy resizing comes from the browser recalculating many elements.

**Comment by thednp** [comment] 2024-07-06 09:32
I've been working on an example to showcase the problem but `createSize` just won't play nice, it will crash the browser in a split second. So I'm pasting here an updated `useResizeObserver` version with configurable `debounce` and `onResize` callback.

```tsx
import { onCleanup, createSignal } from 'solid-js';

type Box = { width: number; height: number };
type ResizeHookProps = { timeout: number, onResize?: (box: Box) => void };

export function useResizeObserver({ timeout, onResize }: ResizeHookProps = { timeout: 1 }) {
    const [entry, setEntry] = createSignal<Box>();
    let previousObserver: ResizeObserver | undefined;
    let timer: ReturnType<typeof setTimeout> | undefined;

    const customRef = <T extends HTMLElement>(node: T) => {
        if (typeof window === 'undefined' || !('ResizeObserver' in window)) return;

        if (node?.nodeType === Node.ELEMENT_NODE) {
            previousObserver = new ResizeObserver(
                () => {
                    clearTimeout(timer);
                    timer = setTimeout(() => {
                        const width = node.offsetWidth;
                        const height = node.offsetHeight;
                        setEntry({ width, height });
                        if (typeof onResize === 'function') onResize({ width, height });
                    }, timeout);
                }
            );
            previousObserver.observe(node);
        }
    };

    onCleanup(() => {
        if (previousObserver) {
            previousObserver.disconnect();
            previousObserver = undefined;
        }
    });

    return [customRef, entry] as [typeof customRef, typeof entry];
}
```
In my tests, this will never crash, jank or do anything to the resize of a window.

Let me know if you want to see the example I've been working on.

**Comment by GiyoMoon** [comment] 2024-07-08 06:16
Yes a reproduction would be very helpful :) Thanks

**Comment by thednp** [comment] 2024-07-08 15:24
@GiyoMoon as requested:
[solid-resize.zip](https://github.com/user-attachments/files/16131261/solid-resize.zip)

**Comment by GiyoMoon** [comment] 2024-07-09 07:21
Hey @thednp , I'm getting an error on the second page:
<img width="1049" alt="image" src="https://github.com/kobaltedev/kobalte/assets/36984337/ec20ef5c-3e63-41e2-83be-99fd6abc91bc">

**Comment by GiyoMoon** [comment] 2024-07-09 15:36
@thednp Please provide a working reproduction with a step-by-step description on how to reproduce the performance issues you're facing with `createSize`. I'm happy to help but I need something to work with.

**Comment by thednp** [comment] 2024-07-09 17:06
[This component](https://www.solid-ui.com/docs/components/navigation-menu) is using your createSize and it feels janky when resizing the window. First time I noticed it I looked into the code and I saw it's using your implementation and I wanted to say it's not the best.

But anyways, feel free to close this if you don't care or it bothers you. The code I provided was reworked over and over in a couple of hours to get the best possible outcome.

**Comment by GiyoMoon** [comment] 2024-07-09 17:48
Thanks. I briefly looked at the performance tab and it doesn't seem like the `createSize` code is causing any meaningful lag. Most of the blocking comes from animating or repainting the UI.
The Navigation Menu has `transition-property: width,height;` applied. Maybe this could lead to it feeling janky?
Floating UI is also doing a lot of stuff when resizing it seems. It's responsible for all the `resize` events being handled. The resize observer doesn't fire nearly as often here.
![image](https://github.com/kobaltedev/kobalte/assets/36984337/51319527-ffc4-4d01-bd45-d53a78773c6b)

**Comment by jer3m01** [comment] 2024-07-15 20:15
Closing as this doesn't seem to be the cause of performance issues. Happy to reopen if we find benchmarks backing it.

**Closed by jer3m01** 2024-07-15 20:15 UTC
